### ISSUE TITLE
Setup proxy Error

### ISSUE THREAD

**Issue by MrHaxxor** [iddoeldor/frida-snippets#11]
# Code 

Java.perform(function () {
  send("Starting hook proxy bypass");

var ActivityThread = Java.use('android.app.ActivityThread');
var ConnectivityManager = Java.use('android.net.ConnectivityManager');
var ProxyInfo = Java.use('android.net.ProxyInfo');

var proxyInfo = ProxyInfo.$new('10.1.11.42', 8080, ''); // change to null in order to disable the proxy.
var context = ActivityThread.currentApplication().getApplicationContext();
var connectivityManager = Java.cast(context.getSystemService('connectivity'), ConnectivityManager);
connectivityManager.setGlobalProxy(proxyInfo);

});

# ERROR:
TypeError: cannot read property 'getApplicationContext' of null
    at [anon] (duk_hobject_props.c:2384)
    at [anon] (/repl1.js:9)
    at frida/node_modules/frida-java/lib/vm.js:43
    at M (frida/node_modules/frida-java/index.js:347)
    at frida/node_modules/frida-java/index.js:333
    at input:1

**Comment by iddoeldor** [comment]
`getApplicationContext` should execute after `onCreate`.. you failed the race.
