### ISSUE TITLE
frida how to hook sub_xxxxx

### ISSUE THREAD

**Issue by github410117** [iddoeldor/frida-snippets#9]
![image](https://user-images.githubusercontent.com/15375736/64092187-35985c00-cd86-11e9-8b34-0f74b922a999.png)
Like this funcion in IDA, how to hook in frida，iOS
Hope to receive your reply，Thx

**Comment by iddoeldor** [comment]
```js
Interceptor.attach(Module.findBaseAddress('YourModule').add(0x15994), {
  onEnter: function (args) { 
    console.log('invoked'); 
  }
});
```
